name: test-matlab

on:
  push:
    branches: [matlab]

jobs:
  run:
    name: Generate coverage report for MATLAB ${{ matrix.matlab-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        matlab: [latest]
        with_optim_toolbox: [yes]

    steps:

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Clone MatCUTEst
        uses: actions/checkout@v4
        with:
          repository: matcutest/matcutest_compiled
          path: matcutest

      - name: Cache MATLAB  # N.B.: Clear the cache when the `latest` version of MATLAB changes in March and September
        uses: actions/cache@v3.3.2
        with:
          path: ${{ runner.tool_cache }}/MATLAB
          key: ${{ matrix.os }}-${{ matrix.matlab }}

      - name: Set up MATLAB with optimization toolbox
        if: ${{ matrix.with_optim_toolbox == 'yes' }}
        uses: matlab-actions/setup-matlab@v1
        with:
          release: ${{ matrix.matlab }}
          products: Optimization_Toolbox

      - name: Install MatCUTEst
        uses: matlab-actions/run-command@v1.2.2
        with:
          command: |
            root_dir = pwd()

            % Install MatCUTEst
            cd(fullfile(root_dir, 'matcutest')); install(); cd(root_dir);

            % Add MatCUTEst to the MATLAB path
            addpath("/home/runner/.local/matcutest");
            savepath;

            % Check the installation
            help matcutest, which('macup'), which('decup'), which('secup')

      - name: Run MATLAB Tests
        uses: matlab-actions/run-command@v1.2.2
        with:
          command: |
            % Add MatCUTEst to the MATLAB path
            addpath("/home/runner/.local/matcutest");
            help matcutest, which('macup'), which('decup'), which('secup')

            % Navigate to the directory containing runTest.m
            cd(fullfile(getenv('GITHUB_WORKSPACE'), 'matlab', 'OptiProfiler'));
            
            % Now run the tests
            runTests;

            % Exit MATLAB
            exit

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml